#
# conductor:server - Build Conductor UI
#
# ===========================================================================================================
# 1. Builder stage 2
# ===========================================================================================================
FROM alpine:3.20 AS ui-builder
ARG YARN_OPTS

LABEL maintainer="Orkes OSS <oss@orkes.io>"

# Install dependencies
RUN apk add --update nodejs npm yarn

COPY ./ui ./conductor/ui
COPY ./docker/ui ./conductor/docker/ui
WORKDIR /conductor/ui

# Include monaco sources into bundle (instead of using CDN)
ENV REACT_APP_MONACO_EDITOR_USING_CDN=false
ENV REACT_APP_ENABLE_ERRORS_INSPECTOR=true
RUN YARN_NETWORK_TIMEOUT=600000 yarn ${YARN_OPTS} install && cp -r node_modules/monaco-editor public/ && yarn ${YARN_OPTS} build
RUN ls -ltr
RUN echo "Done building UI"


FROM nginx:1.28.1-alpine3.23

# UI static assets
COPY --from=ui-builder /conductor/ui/build /usr/share/nginx/html

# nginx template: official entrypoint will envsubst templates automatically
COPY --from=ui-builder /conductor/docker/ui/nginx/nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 5000
